name: 's3-app-configure-action'

description: 'Github action to help synchronize configuration files to an s3 bucket'

branding:
  icon: database
  color: blue

inputs:
  bucket:
    description: 'S3 bucket name to store and sync configurations'
    required: true
  source:
    description: 'Source file that should be synced'
    required: true
  destination:
    description: 'Destination path on s3 bucket including final file name'
    required: true
  aws_access_key:
    description: 'AWS Access Key Id'
    required: true
  aws_secret_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region (default us-east-1)'
    required: false
  dry_run:
    description: 'Do not create any persistent changes over the configurations and just show an overview of the changes'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
